`timescale 1ns / 1ps

module UART_Receiver #(
    parameter clk_freq  = 100_000_000,
    parameter baud_rate = 9600
)(
    input clk_fpga,
    input reset_button,
    input RxD,

    output reg [7:0] RxData,
    output reg [7:0] LED,
    output reg       done
);

    // =========================================================
    // UART parameters
    // =========================================================

    parameter div_sample  = 4;   // 4x oversampling

    localparam integer div_counter =
                    clk_freq / (baud_rate * div_sample);

    localparam integer mid_sample =
                    div_sample / 2;

    // Number of UART bits:
    // start + 8 data + stop = 10 bits
    localparam integer total_bits = 10;


    // =========================================================
    // Counters
    // =========================================================

    reg [13:0] baudrate_counter;
    reg [2:0]  sample_counter;
    reg [3:0]  bit_counter;


    // =========================================================
    // Shift register
    //
    // [9] = stop bit
    // [8:1] = 8 data bits
    // [0] = start bit
    // =========================================================

    reg [9:0] shift_register;


    // =========================================================
    // FSM
    // =========================================================

    localparam IDLE    = 1'b0;
    localparam RECEIVE = 1'b1;

    reg state;
    reg next_state;


    // =========================================================
    // Control signals generated by FSM
    // =========================================================

    reg clear_bitcounter;
    reg inc_bitcounter;

    reg inc_samplecounter;
    reg clear_samplecounter;

    reg shift;


    // =========================================================
    // Sequential logic
    // =========================================================

    always @(posedge clk_fpga) begin

        if (reset_button) begin

            state            <= IDLE;

            baudrate_counter <= 0;
            sample_counter   <= 0;
            bit_counter      <= 0;

            shift_register   <= 0;

            RxData           <= 0;
            LED              <= 0;

            done             <= 0;

        end

        else begin

            state <= next_state;

            // -------------------------------------------------
            // Generate 4x baud sampling tick
            // -------------------------------------------------

            if (baudrate_counter == div_counter-1) begin

                baudrate_counter <= 0;

                // Sample counter
                if (inc_samplecounter)
                    sample_counter <= sample_counter + 1;

                if (clear_samplecounter)
                    sample_counter <= 0;


                // Bit counter
                if (inc_bitcounter)
                    bit_counter <= bit_counter + 1;

                if (clear_bitcounter)
                    bit_counter <= 0;


                // Shift received bit
                if (shift)
                    shift_register <=
                        {RxD, shift_register[9:1]};

            end

            else begin

                baudrate_counter <= baudrate_counter + 1;

            end


            // -------------------------------------------------
            // done is a one-clock pulse
            // -------------------------------------------------

            done <= 1'b0;

        end

    end


    // =========================================================
    // FSM / control logic
    // =========================================================

    always @(*) begin

        // Default values
        next_state = state;

        inc_samplecounter   = 1'b0;
        clear_samplecounter = 1'b0;

        inc_bitcounter      = 1'b0;
        clear_bitcounter    = 1'b0;

        shift = 1'b0;


        case (state)

            // =================================================
            // IDLE
            // =================================================

            IDLE: begin

                if (RxD == 1'b0) begin

                    // Start bit detected

                    next_state = RECEIVE;

                    clear_samplecounter = 1'b1;
                    clear_bitcounter    = 1'b1;

                end

            end


            // =================================================
            // RECEIVE
            // =================================================

            RECEIVE: begin

                // Count the 4 samples belonging to
                // the current UART bit

                inc_samplecounter = 1'b1;


                // -------------------------------------------------
                // Sample at middle of UART bit
                // -------------------------------------------------

                if (sample_counter == mid_sample) begin

                    shift = 1'b1;

                end


                // -------------------------------------------------
                // Four samples completed
                // Move to next UART bit
                // -------------------------------------------------

                if (sample_counter == div_sample-1) begin

                    clear_samplecounter = 1'b1;
                    inc_bitcounter      = 1'b1;

                end


                // -------------------------------------------------
                // All 10 bits received
                // -------------------------------------------------

                if (bit_counter == total_bits-1) begin

                    next_state = IDLE;

                end

            end


            default: begin

                next_state = IDLE;

            end

        endcase

    end


    // =========================================================
    // Finish reception
    //
    // Extract:
    //
    // shift_register[8:1] = received data
    // =========================================================

    always @(posedge clk_fpga) begin

        if (reset_button) begin

            RxData <= 8'h00;
            LED    <= 8'h00;
            done   <= 1'b0;

        end

        else begin

            if ((state == RECEIVE) &&
                (bit_counter == total_bits-1) &&
                (sample_counter == div_sample-1)) begin

                RxData <= shift_register[8:1];

                LED <= shift_register[8:1];

                done <= 1'b1;

            end

        end

    end

endmodule
